# image will be published to ghcr.io/<user>/<name>
name: bluefin-nvidia-laptop-hardened
# description will be included in the image's metadata
description: "Bluefin nvidia with some hardening applied, for laptops"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-nvidia
image-version: 39

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common-files.yml
  - from-file: common/bluefin-packages.yml
  - from-file: common/gui-packages.yml
  - from-file: common/common-packages.yml
  - from-file: recipes/laptop/laptop-bling.yml
  - from-file: common/common-scripts.yml
  - from-file: common/gui-scripts.yml
  - from-file: common/bluefin-scripts.yml
  - from-file: common/disableuserns-packages.yml
  - from-file: common/disableuserns-scripts.yml
  - from-file: common/nvidia-laptop-gnome-cinnamon-scripts.yml
  - from-file: common/nvidia-laptop-scripts.yml
  - type: yafti 