# image will be published to ghcr.io/<user>/<name>
name: server-main-userns-hardened
# description will be included in the image's metadata
description: "ucore with some hardening applied"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: stable

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common-files.yml
  - from-file: common/server-files.yml
  - from-file: common/server-scripts.yml
  - from-file: common/common-packages.yml
  - from-file: common/common-scripts.yml
  - type: signing
