# image will be published to ghcr.io/<user>/<name>
name: server-nvidia-hardened
# description will be included in the image's metadata
description: "base nvidia with some hardening applied"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/fedora-coreos
image-version: stable-nvidia-zfs

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common-files.yml
  - from-file: common/server-scripts.yml
  - from-file: common/common-packages.yml
  - from-file: common/common-bling.yml
  - from-file: common/common-scripts.yml
  - from-file: common/disableuserns-packages.yml
  - from-file: common/disableuserns-scripts.yml