# image will be published to ghcr.io/<user>/<name>
name: startingpoint
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules that will be executed in order
# you can include multiple of the same module
modules:
  - type: rpm-ostree
    repos: 
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - python3-pip
      - libadwaita
    remove:
      - firefox
      - firefox-langpacks

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # these are the silverblue nix installer scripts from dnkmmr69420
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, https://github.com/ublue-os/yafti will be installed and set up
    custom-flatpaks: # this section is optional
      - Celluloid: io.github.celluloid_player.Celluloid
      - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh 