type: bling # configure what to pull in from ublue-os/bling
install:
  - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
              # in your custom.just (added by default) or local justfile
  # - laptop 
  # - ublue-update # https://github.com/ublue-os/ublue-update
  # - 1password # install 1Password (stable) and `op` CLI tool
  # - dconf-update-service # a service unit that updates the dconf db on boot
  # - devpod # https://devpod.sh/ as an rpm
  # - gnome-vrr # enables gnome-vrr for your image
  # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
  # - laptop # installs TLP and configures your system for laptop usage
  # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section