# image will be published to ghcr.io/<user>/<name>
name: cinnamon-nvidia-hardened
# description will be included in the image's metadata
description: "Cinnamon nvidia with some hardening applied"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cinnamon-nvidia
image-version: 39

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/gui-packages.yml
  - from-file: common/common-packages.yml
  - from-file: common/disableuserns-packages.yml
  - from-file: common/gui-scripts.yml
  - from-file: common/disableuserns-scripts.yml
  - from-file: common/cinnamon-scripts.yml
  - from-file: common/common-files.yml
  - from-file: common/common-scripts.yml
  - type: signing
  - type: yafti 