type: rpm-ostree
repos: 
  - https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/repo/fedora-39/secureblue-hardened_malloc-fedora-39.repo
  - https://copr.fedorainfracloud.org/coprs/secureblue/bubblejail/repo/fedora-39/secureblue-bubblejail-fedora-39.repo
install:    
  - lm_sensors
  - lynis
  - hardened_malloc
  - chkrootkit




